version: '3'
volumes:
    redis_volume:
    postgres_data:
        driver: 'local'

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: "postgres_db"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: testDb
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/sql:/docker-entrypoint-initdb.d
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
  # redis_cluster1:
  #   build:
  #     context: ./redis
  #     dockerfile: DockerfileRedisCluster
  #   ports:
  #     - 7000-7005:7000-7005
  #   environment:
  #     CLUSTER_PORTS: "7000 7001 7002 7003 7004 7005"
  #     SLAVES_PER_MASTER: 1
  #   volumes:
  #     - ./tmp/redis/redis_cluster1:/data
  #   container_name: redis_cluster1
  # 
  # redis_cluster2:
  #   build:
  #     context: ./redis
  #     dockerfile: DockerfileRedisCluster
  #   ports:
  #     - 7010-7015:7010-7015
  #   environment:
  #     CLUSTER_PORTS: "7010 7011 7012 7013 7014 7015"
  #     SLAVES_PER_MASTER: 1
  #   volumes:
  #     - ./tmp/redis/redis_cluster2:/data
  #   container_name: redis_cluster2
